apiVersion: v1
kind: Service
metadata:
    name: condormanager
    labels:
        app: condor
spec:
    type: ClusterIP
    ports:
        - port: 9618
    selector:
        app: condor
---
apiVersion: v1
kind: Pod
metadata:
    name: condormanager
    labels:
        app: condor
spec:
    containers:
    - name: condor
      image: condor:b1
      ports:
          - containerPort: 9618
