apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: condorexternal
spec:
    replicas: 6
    template:
        metadata:
            labels:
                app: nodes
        spec:
            containers:
            - name: condorexternal
              image: srp3/condorexternal:v15
              ports:
                  - containerPort: 9618
